modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/The-Acronym-Coders/QuantumQuarry/issues"
[[mods]]
modId="quantumquarry"
version="${file.version}"
displayName="Quantum Quarry"
authors="Lanse505"
description='''
'''